spring:
  elasticsearch:
    rest:
      uris:
        - 192.168.65.206:9200
      username: elastic
      password: elastic

logging:
  level:
    org.springframework.data.elasticsearch.core: DEBUG
    org.elasticsearch.client: TRACE
    org.apache.http: TRACE
