spring:
  elasticsearch:
    rest:
      uris:
        - 122.9.35.11:19200
      username: elastic
      password: kqinfo@elastic*2022

logging:
  level:
    org.springframework.data.elasticsearch.core: DEBUG
    org.elasticsearch.client: TRACE
    org.apache.http: TRACE